# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Heejae Yoo
#title: Senior Network System Administrator
email: heejaeyoo.4@gmail.com
#website: www.github.com/sproogen/resume-theme

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: facespics
github_username:  daniehjyoo
# stackoverflow_username: "00000001"
# dribbble_username: 
# facebook_username: 
# flickr_username: 
#instagram_username: 
linkedin_username: heejae-yoo
# xing_username: 
# pinterest_username: 
#youtube_username: 
# googleplus_username: +
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/20210722_163102.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Heejae and I'm a graduate of University of Texas at Dallas as a Bachleor of Computer Science. 
  Since graduation I've been working on self improving coding skills and strengthening it with the knowledge I obtained throughout my years working for my degree. 
  I have experience making small soft programs and web apps.

  I am most skilled in: <mark>Java</mark>,  <mark> Python</mark> and, of course <mark>Gaming!</mark> 

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: EMR Webapp
        link: https://github.com/TaHB-CS-Project
        # link_text: Project Website
        additional_links:
          - title:  EMR Webapp
            icon: fab fa-github
            url: https://github.com/TaHB-CS-Project
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Built a new website using Golang and PostgreSQL to help doctors get patient data digitized in rural areas of India. Increased patient data retrieval by reducing the paper trail.
        description: | # this will include new lines to allow paragraphs
          This project was started for the group to tackle a big project together and learn collabaration and as a way of learning <mark>Full Stack Development</mark>.
          The website was hosted and maintained through a docker container on an EC2 instance on AWS. 
          I have learned working on the backend with GO and maintaining the database needed with PostgreSQL through this and happy to have this in my portfolio.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: University of Texas at Dallas
        caption: 2019 - 2021
        sub_title: BSc Computer Science
        # quote: >
        #  Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          I transfered into UTD from a college that I was working through the Texas CORE requirements alongside part time working.
          I spent then the 2 years into taking the computer science courses at UTD where I learned core developing concepts, techniques, and the theory of the science. 
          I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.


  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Cooking
      - Gaming
      - Working out

     # - [hyperlink](link)s
     # Look at this cool image  
     # ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
